trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '21'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          - script: echo "Setting JAVA_HOME to JDK 21 location."
            displayName: 'Set JAVA_HOME to JDK 21'

          - task: Cache@2
            displayName: configure gradle caching
            continueOnError: true
            inputs:
              key: 'gradle | "$(Agent.OS)" $(Pipeline.Workspace)/build.gradle'
              restoreKeys: |
                gradle | "$(Agent.OS)"
                gradle
              path: '$(Pipeline.Workspace)/s/.gradle'

          #            inputs:
          #              key: 'gradle | "$(Agent.OS)" $(Pipeline.Workspace)/build.gradle'
          #              restoreKeys: |
          #                gradle | "$(Agent.OS)"
          #                gradle
          #              path: '$(Pipeline.Workspace)/s/.gradle'

          - task: Gradle@2
            displayName: 'build service'
            inputs:
              gradleWrapperFile: '$(Pipeline.Workspace)/s/account-service/gradlew'
              workingDirectory: '$(Pipeline.Workspace)/s/account-service'
              gradleOptions: '-Dorg.gradle.daemon=false'
              tasks: '--info test'

          - publish: $(Pipeline.Workspace)/s/account-service/azure
            artifact: azure