apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-scrape
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring   # namespace where the service account is created
roleRef:
  kind: ClusterRole
  name: prometheus-scrape
  apiGroup: rbac.authorization.k8s.io